// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSXDownloader.MVVM.Models;

#nullable disable

namespace PSXDownloader.Migrations
{
    [DbContext(typeof(PSXDataContext))]
    [Migration("20221005165157_InitialRelease")]
    partial class InitialRelease
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("PSXDownloader.MVVM.Models.PSXDatabase", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PSXDatabases");
                });
#pragma warning restore 612, 618
        }
    }
}
